### ISSUE TITLE
rbc_mesh_stop not working

### ISSUE THREAD

**Issue by oldrich-s** [NordicSemiconductor/nRF51-ble-bcast-mesh#102]
I would like to initialize rbc in stopped state so I do:

```
err_code = rbc_mesh_init(init_params);
APP_ERROR_CHECK(err_code);

err_code = rbc_mesh_stop();
APP_ERROR_CHECK(err_code);
```

However when I measure current it looks like the rbc mesh is actually not stopped. Can I call rbc_mesh_stop just after rbc_mesh_init?

**Comment by oldrich-s** [comment]
I have rewritten my code to bypass the issue. Now the problem I face is that from time to time, although I call rbc_mesh_stop from app_timer the mesh does not actually get stopped. Is there any way how to make sure that the mesh will stop?

**Comment by trond-snekvik** [comment]
Hi, I wrote a hotfix for your issue, as it was caused by a bug which required more than a couple of lines to fix. You can find it here: https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/tree/hotfix_issue_102. The branch should address both stop right after init and odd stop behavior, could you help us verify this?

**Comment by oldrich-s** [comment]
I have tested the hotfix for the last 24 hours and it seems to work fine. Thanks a lot!
