### ISSUE TITLE
mesh feedback function

### ISSUE THREAD

**Issue by ghost** [NordicSemiconductor/nRF51-ble-bcast-mesh#27]
Hi Trond,

I met a problem as I wanna to add a feedback function to this mesh system. Think of this, the node could be asked from nearby nodes or timed itself to put it's state message into mesh network, so user could get the state even if it's out of sight. Maybe it'll does message conficts between nodes but I think this function could be worked under some restrictions.

The question is I don't kown where should I add this feedback packet.properly. What data format is like. So I can get the message from application and send it to the user. And please give some suggestion on this function.

**Comment by trond-snekvik** [comment]
Hi,
If I understand you correctly, you could allocate a separate characteristic per device whose state you would like to see. This wouldn't scale very well though, as the database would fill up pretty quickly.. I'm not sure if creating just a single state characteristic for the entire network would work very well, as the amount of lost status packets could be pretty large, depending on your network size. Some devices may even stay "invisible" for their entire lifetime, as their status is overwritten by their neighbors all the time. It might work fine if you only update the status like once a minute or something for each device (make sure to randomize the intervals!), but yeah.

An alternate approach could be to allocate the characteristic the other way around. If you allocate a single characteristic for state query for the entire network, you could flood a request from your smartphone or gateway to get the status of a specific device in the network. This message could be flooded through the mesh unaltered until it reaches the target device. When the target device gets the query, and sees that it is the target, it could write to the characteristic (with status value and whatnot), and flood this packet back through the network. This approach allows you to pull it off with minimal memory footprint, but may impose a significant response time. Also, you would have to know the address of the device you want a status update from.
Could this be a fitting solution? Was it unclear? I came up with this now, so we haven't tested it, and I can't guarantee that there are no pitfalls, but I think some version of this could be the best approach for this problem. 

---

Anway, you could create a struct to fill into the payload of the regular characteristic in order to create fields for the various data required for both the query and the response. Something like this might work:

``` C
typedef struct
{
    uint8_t type; // 0 = query, 1 = response
    union
    {
        struct
        {
            ble_addr_t target;
            ble_addr_t sender;
        } query;
        struct
        {
            uint8_t power_level;
            uint8_t BLE_name[16];
            uint8_t is_connected;
            uint8_t num_chars;
        } response;
    } param;
} feedback_t;
```

No matter which solution you go by, I really recommend keeping your data inside the characteristic payload you supply to the API with the `rbc_mesh_value_set()`, as this is the only supported way to transfer data right now. You could choose to go into the library and make your own system, but it could break some existing functionality, and might be a lot of work.
