### ISSUE TITLE
What's suggested schema to control single node of mesh ?

### ISSUE THREAD

**Issue by itrs** [NordicSemiconductor/nRF51-ble-bcast-mesh#43]
Currently whole mesh share a view of handle-value pair table. What's suggested way to send message to specified node ? My idea is to specify each node with a id and associate the id to handle. So handle 0 is for node 0, handle 1 is for node 1 ... .Any other suggestion on such purpose schema design ?

**Comment by trond-snekvik** [comment]
This is the way we currently recommend, but it has some issues - if two devices in different parts of the mesh try to write to node 1 at the same time, they will do so with the same version number, but different data. This triggers a conflict in devices that lead up to the target device, and this device has to choose which packet to forward. 

An alternative approach which doesn't have this problem, is to switch it around, so that each handle is only seeded by a single device. For unicasting, you could add your own address field at the beginning of the payload, but this would obviously alter your effective payload length.

Choosing between these two is obviously a tradeoff, and you should use whatever fits your application :)

**Comment by olsky** [comment]
I was facing the same dilemma, first tried to allocate a handle per node, but it was not very effective in my case. For the test case, I was using some of older rev chips with less memory, so the number of handles was limited, thus with more nodes in test -- the handles will become a bottleneck.

Currently I'm experimenting with round-robin scheduling: cycling thru handles, so each node keeps a track of last used handle and will use the next one for transmission. When the last handle is reached -- it will drop the the first available. 

I have also assigned one handle to keep track of last used handle, so it helps to synchronize it a bit :-)

**Comment by trond-snekvik** [comment]
@olsky The sdk-8-support branch has a built in LRU-cache for handles, have you experimented with the settings for it? It allows you to control the memory footprint on each device, so that you don't have to scale with the number of devices.

**Comment by olsky** [comment]
@trond-snekvik thank you, I will check it.

do you mean changing the RBC_MESH_HANDLE_CACHE_ENTRIES and RBC_MESH_DATA_CACHE_ENTRIES values?

**Comment by trond-snekvik** [comment]
Yes :)

**Comment by olsky** [comment]
that was fast! :-) thanks!
